volumes:
  db:
  snapshots:
  edge-config-cache:
  influxdb-data:
  grafana-data:

networks:
  monitoring_net:

services:
  db:
    image: postgres:14-alpine
    network_mode: host
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dp_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
  edge_config:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/edge-config:latest
    network_mode: host
    depends_on:
      db:
        condition: service_healthy
    command: [
      --json_db_file=/data/event_templates.json,
      --cache_dir=/tmp/cache,
      -logtostderr
    ]
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=dp_db
      - DB_PORT=5432
      - DB_HOST=0.0.0.0
      - DP_IRIS_ADDRESS=0.0.0.0:50052
    ports:
      - "50051:50051"
    volumes:
      # NOTE: the mounted location needs to match --cache_dir
      - edge-config-cache:/tmp/cache
    restart: always
  events_server:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/events-server:latest
    network_mode: host
    ports:
      - "50053:50053"
    volumes:
      - snapshots:/videos
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=dp_db
      - DB_PORT=5432
      - DB_HOST=0.0.0.0
    depends_on:
      db:
        condition: service_healthy
    command: [
      -logtostderr
    ]

  usb_cameras:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/usb-cameras:latest
    network_mode: host
    privileged: true
    ports:
      - "50054:50054"
    volumes:
      - /dev/v4l/by-id:/dev/v4l/by-id
    command: [
      -logtostderr
    ]
    restart: always

  iris_server:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/iris-server:latest
    network_mode: host
    privileged: true
    ports:
      - "50052:50052"
      - "8443:8443/udp"
      - "54000-54100:54000-54100/udp"
    # command: "--save_dir /videos/snapshots"
    environment:
      - EVENTS_SERVER_HOST=0.0.0.0
      # TODO(chris): added for X11
      - DISPLAY=$DISPLAY
      # - GST_DEBUG=*:6
      - HAILO_MONITOR=1

    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      # Uncomment for Hailo
      - /dev/hailo0:/dev/hailo0
      # - /dev/hailo1:/dev/hailo1
      # - /dev/hailo1:/dev/hailo1
      # Uncomment for coral PCIe
      # - /dev/apex_0:/dev/apex_0
      # Uncomment for coral USB
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - snapshots:/videos
      - /dev/dri:/dev/dri
      - /dev/:/dev/
      # - /dev/hailo1:/dev/hailo1
      - /dev/bus/usb:/dev/bus/usb
      # TODO(chris): added for X11
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/hmon_files:/tmp/hmon_files
      - /dev/v4l/by-id:/dev/v4l/by-id
    group_add:
      - "109"
      - "110"
      - "44"
      - "46"
    restart: always
    depends_on:
      - webrtc

  dp-envoy:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/envoy-proxy:latest
    network_mode: host
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9090:9090"
    environment:
      - ENVOY_UID=0
      - DP_EDGE_CONFIG_HOSTNAME=0.0.0.0
      - DP_EVENTS_SERVER_HOSTNAME=0.0.0.0
    depends_on:
      - edge_config
  frontend:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/frontend:latest
    network_mode: host
    ports:
      - "8082:8082"
    environment:
      - DP_ENVOY_HOSTNAME=0.0.0.0
      - DP_WEBRTC_HOSTNAME=0.0.0.0
    depends_on:
      - dp-envoy

  webrtc:
    network_mode: host
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/webrtc:latest
    ports:
      - "7777:7777"
    restart: always

  # Metrics and monitoring part of the deployment
  influxdb:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/influxdb:latest
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegrafpassword
    ports:
      - "8086:8086"
    networks:
      - monitoring_net

  telegraf:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/telegraf:latest
    privileged: true
    depends_on:
      - influxdb
    volumes:
      # Mount RAPL directory
      - /sys/class/powercap:/sys/class/powercap:ro
      - /sys/devices/virtual/powercap:/sys/devices/virtual/powercap:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /tmp/logs:/tmp/logs
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ROOT=/rootfs
    networks:
      - monitoring_net

  grafana:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    #volumes:
    #  - grafana-data:/var/lib/grafana:rw

    networks:
      - monitoring_net

  hailo_monitor:
    image: us-central1-docker.pkg.dev/deepperception-challenger/demo1/hailo_monitor:latest
    # So hailo monitor files can be read from iris
    privileged: true
    volumes:
      - /tmp/hmon_files:/tmp/hmon_files
      - /tmp/logs:/tmp/logs
      - /dev:/dev
    # devices:
    #   - /dev/hailo0:/dev/hailo0
    #   - /dev/hailo1:/dev/hailo1
